---
- import_role:
    name: docker

- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

- name: Create Docker volume for Jenkins
  docker_volume:
    name: jenkins_home

