- name: Install Docker on all nodes
  hosts: all
  become: true
  roles:
    - docker

- name: Provision CI server (Jenkins)
  hosts: ci
  become: true
  roles:
    - jenkins

- name: Provision Monitoring server
  hosts: monitoring
  become: true
  roles:
    - monitoring

